---
# Source: xposer/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: xposer
  labels:
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.15
    chart: "xposer-v0.0.15"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: xposer
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      labels:
        app: xposer
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /configs/config.yaml
        image: "stakater/xposer:v0.0.15"
        imagePullPolicy: IfNotPresent
        name: xposer
        volumeMounts:
        - mountPath: /configs
          name: config-volume
      serviceAccountName: xposer
      volumes:
      - configMap:
          name: xposer
        name: config-volume
              
---
# Source: xposer/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.15
    chart: "xposer-v0.0.15"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: 
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.15
    chart: "xposer-v0.0.15"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "route.openshift.io"
    resources:
      - ingresses
      - routes
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - watch
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: 
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.15
    chart: "xposer-v0.0.15"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xposer-role
subjects:
  - kind: ServiceAccount
    name: xposer
    namespace: default
---
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: 
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.15
    chart: "xposer-v0.0.15"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer-configmap-role-default
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: 
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.15
    chart: "xposer-v0.0.15"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer-configmap-role-binding-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xposer-configmap-role-default
subjects:
  - kind: ServiceAccount
    name: xposer
    namespace: default
---
---
# Source: xposer/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: xposer
    group: com.stakater.platform
    provider: stakater
    version: v0.0.15
    chart: "xposer-v0.0.15"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: xposer
data:
  config.yaml: |-
    domain: stakater.com
    ingressURLTemplate: "{{.Service}}.{{.Namespace}}.{{.Domain}}"
    ingressURLPath: /
    ingressNameTemplate: "{{.Service}}"
    tls: false
  default-url : default.com 
